# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipe < Formula
  desc "CI-friendly pipeline runner inspired by Taskfile"
  homepage "https://github.com/idestis/pipe"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/idestis/pipe/releases/download/v1.1.0/pipe-1.1.0-darwin-amd64.tar.gz"
      sha256 "f7c1fdac035579701c8b313b8320254d2559118ceb2d0bfd2db12a2b90402631"

      def install
        bin.install "pipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/idestis/pipe/releases/download/v1.1.0/pipe-1.1.0-darwin-arm64.tar.gz"
      sha256 "d52096ef27693efb9ede69831dcc3c77c6238f094f98151688839b77009734d1"

      def install
        bin.install "pipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/idestis/pipe/releases/download/v1.1.0/pipe-1.1.0-linux-amd64.tar.gz"
      sha256 "33251d8428df72681e718e443286cb65975c698b1775a986d78913f408c41915"
      def install
        bin.install "pipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idestis/pipe/releases/download/v1.1.0/pipe-1.1.0-linux-arm64.tar.gz"
      sha256 "def650cf2f9467b9d114a0d814a5f986380b62cbd76c21672fcedc4b8645a665"
      def install
        bin.install "pipe"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pipe --version")
  end
end
