# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipe < Formula
  desc "CI-friendly pipeline runner inspired by Taskfile"
  homepage "https://github.com/getpipe-dev/pipe"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.2.0/pipe-2.2.0-darwin-amd64.tar.gz"
      sha256 "d587bb886e150dcdd18dc26d43b7ba8f926101ba890c55eeafbf096b9fbb2600"

      def install
        bin.install "pipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.2.0/pipe-2.2.0-darwin-arm64.tar.gz"
      sha256 "0471076a81f7aab2d3c3b0a8e90b5e000c642ffcb40954859342aa7ef2c164cf"

      def install
        bin.install "pipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.2.0/pipe-2.2.0-linux-amd64.tar.gz"
      sha256 "3fe44b9450169264c05a28398033b475f89f58ecdf7f21eddc8199899299f7e9"
      def install
        bin.install "pipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.2.0/pipe-2.2.0-linux-arm64.tar.gz"
      sha256 "95c757d4296aab6f7631278f7b52d9ccecd1f9e6d27f960d2e264c76e4a6064a"
      def install
        bin.install "pipe"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pipe --version")
  end
end
